const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg',W=1500,H=1300;
let people=[],bands=[],cities=[],memberships=[],selected=null,zoom=1,fullGraph=false,viewX=W/2,viewY=H/2;
const svg=$('#graph'),key=(t,id)=>t+':'+id,get=(t,id)=>({city:cities,band:bands,person:people}[t]||[]).find(x=>x.id===id);
async function load(){[people,bands,cities,memberships]=await Promise.all(['people','bands','cities','memberships'].map(x=>fetch('data/'+x+'.json').then(r=>r.json())));render()}
function el(t,a={},s=''){const n=document.createElementNS(NS,t);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));if(s)n.textContent=s;return n}
function cityRadius(id){return 40+Math.min(14,bands.filter(b=>b.city===id).length*1.5)}
function bandRadius(n){return Math.max(38,Math.min(54,Math.max(...wrapWords(n.name,12).map(x=>x.length))*3.6+10))}
function nodeRadius(n){return n.type==='city'?cityRadius(n.id):n.type==='band'?bandRadius(n):18}
function wrapWords(value,max){const lines=[];let line='';for(const word of value.split(/\s+/)){if(line&&(line+' '+word).length>max){lines.push(line);line=word}else line+=(line?' ':'')+word}if(line)lines.push(line);return lines}
function mostConnectedPerson(){return people.reduce((best,p)=>{const c=memberships.filter(m=>m.person===p.id).length;return !best||c>best.connections?{...p,connections:c}:best},null)}
function overview(includePeople){const nodes=[...cities.map(x=>({...x,type:'city'})),...bands.map(x=>({...x,type:'band'}))];if(includePeople)nodes.push(...people.map(x=>({...x,type:'person'})));return{nodes,edges:[...bands.map(b=>({from:key('city',b.city),to:key('band',b.id)})),...(includePeople?memberships.map(m=>({from:key('band',m.band),to:key('person',m.person)})):[])]}}
function context(){if(!selected)return overview(fullGraph);if(selected.type==='city'){const bs=bands.filter(b=>b.city===selected.id);return{nodes:[{...get('city',selected.id),type:'city'},...bs.map(x=>({...x,type:'band'}))],edges:bs.map(b=>({from:key('city',selected.id),to:key('band',b.id)}))}}
if(selected.type==='band'){const b=get('band',selected.id),ms=memberships.filter(m=>m.band===selected.id);return{nodes:[{...get('city',b.city),type:'city'},{...b,type:'band'},...ms.map(m=>({...get('person',m.person),type:'person',membershipStatus:m.status})).filter(x=>x.id)],edges:[{from:key('city',b.city),to:key('band',b.id)},...ms.map(m=>({from:key('band',b.id),to:key('person',m.person)}))]}}
const bs=memberships.filter(m=>m.person===selected.id).map(m=>get('band',m.band)).filter(Boolean),cs=[...new Set(bs.map(b=>b.city))].map(id=>get('city',id)).filter(Boolean);return{nodes:[...cs.map(x=>({...x,type:'city'})),...bs.map(x=>({...x,type:'band'})),{...get('person',selected.id),type:'person'}],edges:[...bs.map(b=>({from:key('city',b.city),to:key('band',b.id)})),...bs.map(b=>({from:key('band',b.id),to:key('person',selected.id)}))]}}
function layout(ns,es){const p=new Map(),cx=W/2,cy=H/2,cs=ns.filter(n=>n.type==='city');
if(selected?.type==='band'){const b=get('band',selected.id),members=ns.filter(n=>n.type==='person');p.set(key('city',b.city),{x:190,y:cy});p.set(key('band',b.id),{x:650,y:cy});members.forEach((n,i)=>p.set(key('person',n.id),{x:1160,y:cy+(i-(members.length-1)/2)*100}));return p}
const cols=Math.min(3,Math.ceil(Math.sqrt(cs.length)));cs.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),x=cs.length===1?cx:270+col*480,y=cs.length===1?cy:230+row*420;p.set(key('city',n.id),{x,y})});
const groups=new Map();ns.filter(n=>n.type==='band').forEach(n=>{if(!groups.has(n.city))groups.set(n.city,[]);groups.get(n.city).push(n)});groups.forEach((list,id)=>{const c=p.get(key('city',id))||{x:cx,y:cy},r=list.length>=7?210:list.length>=4?170:130;list.forEach((n,i)=>{const a=2*Math.PI*i/list.length-Math.PI/2;p.set(key('band',n.id),{x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r})})});
ns.filter(n=>n.type==='person').forEach((n,i)=>{const related=es.filter(e=>e.to===key('person',n.id)||e.from===key('person',n.id)).map(e=>p.get(e.to===key('person',n.id)?e.from:e.to)).filter(Boolean),c=related.length?{x:related.reduce((s,q)=>s+q.x,0)/related.length,y:related.reduce((s,q)=>s+q.y,0)/related.length}:{x:cx,y:cy},a=i*2.399963,r=85+(i%6)*24;p.set(key('person',n.id),{x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r})});
const arr=ns.map(n=>({n,p:p.get(key(n.type,n.id))}));for(let k=0;k<36;k++)for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const a=arr[i].p,b=arr[j].p,dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=arr[i].n.type==='person'&&arr[j].n.type==='person'?66:86;if(d<min){const f=(min-d)*.12;a.x-=dx/d*f;a.y-=dy/d*f;b.x+=dx/d*f;b.y+=dy/d*f}}return p}
function appendLabel(group,n,x,y){const lines=wrapWords(n.name,n.type==='city'?13:12),t=el('text',{x,y,'text-anchor':'middle','dominant-baseline':'middle',class:'node-label'});lines.forEach((line,i)=>t.append(el('tspan',{x,dy:i===0?-(lines.length-1)*.55+'em':'1.1em'},line)));group.append(t)}
function render(){const leader=mostConnectedPerson();$('#stats').textContent=cities.length+' cities · '+people.length+' people · '+bands.length+' bands · '+memberships.length+' relationships';$('#tip').textContent=leader?'Tip: '+leader.name+' has the most connections ('+leader.connections+' bands).':'';$('#toggle-graph').textContent=fullGraph?'Show summary view':'Show full network';svg.classList.toggle('focused',!!selected);svg.replaceChildren();const defs=el('defs'),marker=el('marker',{id:'arrowhead',markerWidth:9,markerHeight:9,refX:8,refY:4.5,orient:'auto',markerUnits:'userSpaceOnUse',viewBox:'0 0 9 9'});marker.append(el('path',{d:'M0 0 L9 4.5 L0 9 Z',fill:'#a9bdc8'}));defs.append(marker);svg.append(defs);
const v=context(),p=layout(v.nodes,v.edges),lookup=new Map(v.nodes.map(n=>[key(n.type,n.id),n])),sk=selected&&key(selected.type,selected.id),near=new Set();v.edges.forEach(e=>{if(e.from===sk)near.add(e.to);if(e.to===sk)near.add(e.from)});const eg=el('g');v.edges.forEach(e=>{const a=p.get(e.from),b=p.get(e.to),source=lookup.get(e.from),target=lookup.get(e.to);if(!a||!b||!source||!target)return;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,ra=nodeRadius(source),rb=nodeRadius(target);eg.append(el('line',{x1:a.x+dx/d*(ra+2),y1:a.y+dy/d*(ra+2),x2:b.x-dx/d*(rb+10),y2:b.y-dy/d*(rb+10),class:'edge'+(sk&&(e.from===sk||e.to===sk)?' highlighted':''),'marker-end':'url(#arrowhead)'}))});svg.append(eg);const ng=el('g');v.nodes.forEach(n=>{const q=p.get(key(n.type,n.id)),id=key(n.type,n.id),is=id===sk,dim=sk&&!is&&!near.has(id),g=el('g',{class:'node '+n.type+'-node'+(n.membershipStatus==='former'?' former-member':'')+(is?' selected':'')+(dim?' dimmed':''),tabindex:'0',role:'button','aria-label':n.name});g.append(el('circle',{cx:q.x,cy:q.y,r:nodeRadius(n)}));appendLabel(g,n,q.x,q.y);g.onclick=()=>select(n);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n)}};ng.append(g)});svg.append(ng);const vw=W/zoom,vh=H/zoom;svg.setAttribute('viewBox',(viewX-vw/2)+' '+(viewY-vh/2)+' '+vw+' '+vh);renderResults()}
function select(n){selected={type:n.type,id:n.id};renderDetails(n);render()}
function renderDetails(n){const box=$('#details');box.replaceChildren();const title=document.createElement('strong');title.textContent=n.name;box.append(title);const p=document.createElement('p');if(n.type==='city')p.textContent=bands.filter(b=>b.city===n.id).length+' bands from this city.';else if(n.type==='band'){const ms=memberships.filter(m=>m.band===n.id);p.textContent=(n.from||'')+'–'+(n.to||'present')+(n.reunion?' · reunion in '+n.reunion:'')+' · '+ms.length+' members: '+ms.map(m=>(get('person',m.person)?.name||'')+(m.role?' — '+m.role:'')+(m.status==='former'?' (former)':'')).join(', ')}else p.textContent='Bands: '+memberships.filter(m=>m.person===n.id).map(m=>get('band',m.band)?.name).filter(Boolean).join(', ');box.append(p)}
function renderResults(){const box=$('#results'),q=$('#search').value.trim().toLowerCase();box.replaceChildren();if(!q){const hint=document.createElement('div');hint.className='result hint';hint.textContent='Search for a city, band, or person.';box.append(hint);return}const all=[...cities.map(x=>({...x,type:'city'})),...bands.map(x=>({...x,type:'band'})),...people.map(x=>({...x,type:'person'}))].filter(x=>x.name.toLowerCase().includes(q)).slice(0,20);all.forEach(x=>{const b=document.createElement('button');b.className='result '+x.type;b.textContent=x.name;b.onclick=()=>select(x);box.append(b)})}
function zoomAt(clientX,clientY,factor){const rect=svg.getBoundingClientRect(),fx=Math.max(0,Math.min(1,(clientX-rect.left)/rect.width)),fy=Math.max(0,Math.min(1,(clientY-rect.top)/rect.height)),oldW=W/zoom,oldH=H/zoom,worldX=viewX-oldW/2+fx*oldW,worldY=viewY-oldH/2+fy*oldH;zoom=Math.max(.65,Math.min(2.4,zoom*factor));const newW=W/zoom,newH=H/zoom;viewX=worldX+(0.5-fx)*newW;viewY=worldY+(0.5-fy)*newH;render()}
svg.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.clientX,e.clientY,e.deltaY<0?1.12:1/1.12)},{passive:false});
$('#search').addEventListener('input',renderResults);$('#zoom-in').addEventListener('click',()=>zoomAt(svg.getBoundingClientRect().left+svg.clientWidth/2,svg.getBoundingClientRect().top+svg.clientHeight/2,1.2));$('#zoom-out').addEventListener('click',()=>zoomAt(svg.getBoundingClientRect().left+svg.clientWidth/2,svg.getBoundingClientRect().top+svg.clientHeight/2,1/1.2));$('#zoom-fit').addEventListener('click',()=>{zoom=1;viewX=W/2;viewY=H/2;render()});$('#toggle-graph').addEventListener('click',()=>{fullGraph=!fullGraph;selected=null;zoom=1;viewX=W/2;viewY=H/2;$('#details').textContent='Select a node to explore its connections.';render()});$('#reset').addEventListener('click',()=>{selected=null;zoom=1;viewX=W/2;viewY=H/2;$('#details').textContent='Select a node to explore its connections.';render()});load().catch(e=>$('#details').textContent='Could not load data: '+e);