const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg',W=1500,H=1300;
let people=[],bands=[],cities=[],memberships=[],selected=null,zoom=1,fullGraph=false;
const svg=$('#graph'),key=(t,id)=>t+':'+id,get=(t,id)=>({city:cities,band:bands,person:people}[t]||[]).find(x=>x.id===id);
async function load(){[people,bands,cities,memberships]=await Promise.all(['people','bands','cities','memberships'].map(x=>fetch('data/'+x+'.json').then(r=>r.json())));render()}
function el(t,a={},s=''){const n=document.createElementNS(NS,t);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));if(s)n.textContent=s;return n}
function cityRadius(id){return 24+Math.min(26,bands.filter(b=>b.city===id).length*2.5)}
function mostConnectedPerson(){return people.reduce((best,p)=>{const c=memberships.filter(m=>m.person===p.id).length;return !best||c>best.connections?{...p,connections:c}:best},null)}
function overview(includePeople){const nodes=[...cities.map(x=>({...x,type:'city'})),...bands.map(x=>({...x,type:'band'}))];if(includePeople)nodes.push(...people.map(x=>({...x,type:'person'})));return{nodes,edges:[...bands.map(b=>({from:key('city',b.city),to:key('band',b.id)})),...(includePeople?memberships.map(m=>({from:key('band',m.band),to:key('person',m.person)})):[])]}}
function context(){if(!selected)return overview(fullGraph);if(selected.type==='city'){const bs=bands.filter(b=>b.city===selected.id);return{nodes:[{...get('city',selected.id),type:'city'},...bs.map(x=>({...x,type:'band'}))],edges:bs.map(b=>({from:key('city',selected.id),to:key('band',b.id)}))}}
if(selected.type==='band'){const b=get('band',selected.id),ms=memberships.filter(m=>m.band===selected.id);return{nodes:[{...get('city',b.city),type:'city'},{...b,type:'band'},...ms.map(m=>({...get('person',m.person),type:'person',membershipStatus:m.status})).filter(x=>x.id)],edges:[{from:key('city',b.city),to:key('band',b.id)},...ms.map(m=>({from:key('band',b.id),to:key('person',m.person)}))]}}
const bs=memberships.filter(m=>m.person===selected.id).map(m=>get('band',m.band)).filter(Boolean),cs=[...new Set(bs.map(b=>b.city))].map(id=>get('city',id)).filter(Boolean);return{nodes:[...cs.map(x=>({...x,type:'city'})),...bs.map(x=>({...x,type:'band'})),{...get('person',selected.id),type:'person'}],edges:[...bs.map(b=>({from:key('city',b.city),to:key('band',b.id)})),...bs.map(b=>({from:key('band',b.id),to:key('person',selected.id)}))]}}
function layout(ns,es){const p=new Map(),cx=W/2,cy=H/2,cs=ns.filter(n=>n.type==='city');
if(selected?.type==='band'){const b=get('band',selected.id),members=ns.filter(n=>n.type==='person');p.set(key('city',b.city),{x:210,y:cy});p.set(key('band',b.id),{x:670,y:cy});members.forEach((n,i)=>p.set(key('person',n.id),{x:1160,y:cy+(i-(members.length-1)/2)*92}));return p}
const cols=Math.min(3,Math.ceil(Math.sqrt(cs.length)));cs.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),x=cs.length===1?cx:270+col*480,y=cs.length===1?cy:230+row*420;p.set(key('city',n.id),{x,y})});
const groups=new Map();ns.filter(n=>n.type==='band').forEach(n=>{if(!groups.has(n.city))groups.set(n.city,[]);groups.get(n.city).push(n)});groups.forEach((list,id)=>{const c=p.get(key('city',id))||{x:cx,y:cy},r=list.length>=7?190:list.length>=4?155:120;list.forEach((n,i)=>{const a=2*Math.PI*i/list.length-Math.PI/2;p.set(key('band',n.id),{x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r})})});
ns.filter(n=>n.type==='person').forEach((n,i)=>{const related=es.filter(e=>e.to===key('person',n.id)||e.from===key('person',n.id)).map(e=>p.get(e.to===key('person',n.id)?e.from:e.to)).filter(Boolean),c=related.length?{x:related.reduce((s,q)=>s+q.x,0)/related.length,y:related.reduce((s,q)=>s+q.y,0)/related.length}:{x:cx,y:cy},a=i*2.399963,r=72+(i%6)*22;p.set(key('person',n.id),{x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r})});
const arr=ns.map(n=>({n,p:p.get(key(n.type,n.id))}));for(let k=0;k<32;k++)for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const a=arr[i].p,b=arr[j].p,dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=arr[i].n.type==='person'&&arr[j].n.type==='person'?58:74;if(d<min){const f=(min-d)*.12;a.x-=dx/d*f;a.y-=dy/d*f;b.x+=dx/d*f;b.y+=dy/d*f}}return p}
function render(){const leader=mostConnectedPerson();$('#stats').textContent=cities.length+' ciudades · '+people.length+' personas · '+bands.length+' bandas · '+memberships.length+' relaciones';$('#tip').textContent=leader?'Consejo: '+leader.name+' tiene más conexiones ('+leader.connections+' bandas).':'';$('#toggle-graph').textContent=fullGraph?'Volver a vista resumida':'Mostrar vista completa';svg.classList.toggle('focused',!!selected);svg.replaceChildren();const v=context(),p=layout(v.nodes,v.edges),sk=selected&&key(selected.type,selected.id),near=new Set();v.edges.forEach(e=>{if(e.from===sk)near.add(e.to);if(e.to===sk)near.add(e.from)});const eg=el('g');v.edges.forEach(e=>{const a=p.get(e.from),b=p.get(e.to);if(a&&b)eg.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'edge'+(sk&&(e.from===sk||e.to===sk)?' highlighted':'')}))});svg.append(eg);const ng=el('g');v.nodes.forEach(n=>{const q=p.get(key(n.type,n.id)),id=key(n.type,n.id),is=id===sk,dim=sk&&!is&&!near.has(id),g=el('g',{class:'node '+n.type+'-node'+(n.membershipStatus==='former'?' former-member':'')+(is?' selected':'')+(dim?' dimmed':''),tabindex:'0',role:'button','aria-label':n.name});const r=n.type==='city'?cityRadius(n.id):n.type==='band'?25:18;g.append(el('circle',{cx:q.x,cy:q.y,r}),el('text',{x:q.x,y:q.y+(n.type==='city'?r+20:n.type==='band'?46:37),'text-anchor':'middle'},n.name));if(n.type==='band')g.append(el('text',{x:q.x,y:q.y+63,'text-anchor':'middle',class:'band-years'},n.from+' — '+(n.to||'activa')+(n.reunion?' · reunión '+n.reunion:'')));g.onclick=()=>select(n);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n)}};ng.append(g)});svg.append(ng);const vw=W/zoom,vh=H/zoom;svg.setAttribute('viewBox',((W-vw)/2)+' '+((H-vh)/2)+' '+vw+' '+vh);renderResults()}
function select(n){selected={type:n.type,id:n.id};renderDetails(n);render()}
function renderDetails(n){const box=$('#details');box.replaceChildren();const title=document.createElement('strong');title.textContent=n.name;box.append(title);const p=document.createElement('p');if(n.type==='city')p.textContent=bands.filter(b=>b.city===n.id).length+' bandas originadas aquí.';else if(n.type==='band'){const ms=memberships.filter(m=>m.band===n.id);p.textContent=(n.from||'')+' — '+(n.to||'activa')+(n.reunion?' · reunión '+n.reunion:'')+' · '+ms.length+' miembros: '+ms.map(m=>(get('person',m.person)?.name||'')+(m.status==='former'?' (exmiembro)':'')).join(', ')}else p.textContent='Participaciones: '+memberships.filter(m=>m.person===n.id).map(m=>get('band',m.band)?.name).filter(Boolean).join(', ');box.append(p)}
function renderResults(){const box=$('#results'),q=$('#search').value.trim().toLowerCase();box.replaceChildren();if(!q){const hint=document.createElement('div');hint.className='result hint';hint.textContent='Busca una ciudad, banda o persona.';box.append(hint);return}const all=[...cities.map(x=>({...x,type:'city'})),...bands.map(x=>({...x,type:'band'})),...people.map(x=>({...x,type:'person'}))].filter(x=>x.name.toLowerCase().includes(q)).slice(0,20);all.forEach(x=>{const b=document.createElement('button');b.className='result '+x.type;b.textContent=x.name;b.onclick=()=>select(x);box.append(b)})}
$('#search').addEventListener('input',renderResults);$('#zoom-in').addEventListener('click',()=>{zoom=Math.min(2.2,zoom*1.2);render()});$('#zoom-out').addEventListener('click',()=>{zoom=Math.max(.65,zoom/1.2);render()});$('#zoom-fit').addEventListener('click',()=>{zoom=1;render()});$('#toggle-graph').addEventListener('click',()=>{fullGraph=!fullGraph;selected=null;zoom=1;$('#details').textContent='Selecciona un nodo para explorar sus conexiones.';render()});$('#reset').addEventListener('click',()=>{selected=null;zoom=1;$('#details').textContent='Selecciona un nodo para explorar sus conexiones.';render()});load().catch(e=>$('#details').textContent='No se pudieron cargar los datos: '+e);